spring.application.name=DevLibrary
#TiDB Cloud Database Connection Settings
spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=22fegeSmo2ZFex4.root
spring.datasource.password=8ejpKgsBDX9h3Ph9
# Spring Data JPA settings for automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true