spring.application.name=DevLibrary
#TiDB Cloud Database Connection Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Spring Data JPA settings for automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use Render's port when deployed, otherwise use 8080 locally
server.port=${PORT:8080}